kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-master-node
  namespace: spark-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master-node
  template:
    metadata:
      labels:
        component: spark-master-node
    spec:
      containers:
        - name: spark-master-node
          image: 10.10.1.100:5000/myspark
          command: ["start-master.sh"]
          args: ["--ip spark-master-node", "--webui-port 8080", "--port 7077"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
